language: php

## Cache composer bits
cache:
  directories:
  - $HOME/.composer/cache/files

php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - name: lowest dependencies
      env:
      - dependencies=lowest
    - name: highest dependencies
      env:
      - dependencies=highest

## Install or update dependencies
install:
- composer validate
- if [ -z "$dependencies" ]; then composer install --prefer-dist; fi;
- if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-dist -n; fi;
- if [ "$dependencies" = "highest" ]; then composer update --prefer-dist -n; fi;
- composer show

script:
  - bin/behat
  - bin/behat --profile mink
