language: php

## Cache composer bits
cache:
  directories:
  - $HOME/.composer/cache/files

php:
- 5.6
- 7.0

## Build matrix for lowest and highest possible targets
matrix:
  include:
#    - name: lowest dependencies
#      php: 7.0
#      env:
#      - dependencies=lowest

    - name: 7.1 highest dependencies
      php: 7.1
      env:
      - dependencies=highest

    - name: 7.2 - highest dependencies
      php: 7.2
      env:
      - dependencies=highest

    - name: 7.3 - highest dependencies
      php: 7.3
      env:
      - dependencies=highest


## Install or update dependencies
install:
- composer validate
- if [ -z "$dependencies" ]; then composer install --prefer-dist; fi;
- if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-dist -n; fi;
- if [ "$dependencies" = "highest" ]; then composer update --prefer-dist -n; fi;
- composer show

script:
  - bin/behat
  - bin/behat --profile mink
